var BASE="https://clmcenjnujrtuyjwrnim.supabase.co/functions/v1/";
var AUTH=BASE+"fct-meal-auth", REG=BASE+"fct-meal-register", ADM=BASE+"fct-meal-admin";
var token=localStorage.getItem("fctMealToken")||"", user=null, restaurantId=new URLSearchParams(location.search).get("restaurant")||"", restaurant=null;
var participants=[], adminUsers=[], adminRestaurants=[], adminRecords=[];
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]})}
function msg(id,text,ok){var e=document.getElementById(id);e.className=text?(ok?"ok":"err"):"";e.textContent=text||""}
async function post(url,data){try{var r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});var j=await r.json();return j}catch(e){return {ok:false,message:"서버 연결에 실패했습니다."}}}
function showAuth(mode){document.getElementById("loginForm").classList.toggle("hidden",mode!=="login");document.getElementById("signupForm").classList.toggle("hidden",mode!=="signup");document.getElementById("loginTab").classList.toggle("on",mode==="login");document.getElementById("signupTab").classList.toggle("on",mode==="signup")}
async function loadRestaurant(){if(!restaurantId)return;var j=await post(AUTH,{action:"restaurant_public",restaurant_id:restaurantId});if(j.ok){restaurant=j.restaurant;document.getElementById("restaurantHint").classList.remove("hidden");document.getElementById("restaurantHint").textContent="현재 식당: "+restaurant.name}}
async function doSignup(){var j=await post(AUTH,{action:"signup",employee_no:suNo.value,name:suName.value,department:suDept.value,worker_type:suType.value});msg("signupMsg",j.message,j.ok);if(j.ok){loginNo.value=suNo.value;showAuth("login")}}
async function doLogin(){var j=await post(AUTH,{action:"login",employee_no:loginNo.value,pin:loginPin.value});if(j.requires_pin){pinRow.classList.remove("hidden");msg("loginMsg",j.message,false);return}if(!j.ok){msg("loginMsg",j.message,false);return}token=j.token;localStorage.setItem("fctMealToken",token);user=j.user;await enter()}
async function restore(){if(!token)return;var j=await post(AUTH,{action:"me",token:token});if(j.ok){user=j.user;await enter()}else{localStorage.removeItem("fctMealToken");token=""}}
async function enter(){authView.classList.add("hidden");userView.classList.remove("hidden");who.textContent=user.name+" · "+user.department+" · "+(user.role==="USER"?"일반":user.role==="OWNER"?"최초 마스터":"마스터");identity.innerHTML="<b>"+esc(user.name)+"</b> · "+esc(user.department)+" · "+esc(user.employee_no)+" · "+esc(user.worker_type==="OP"?"OP":"엔지니어");if(restaurant){restaurantName.textContent=restaurant.name;mealBox.classList.remove("hidden");noQr.classList.add("hidden")}else{mealBox.classList.add("hidden");noQr.classList.remove("hidden")}addTypeWrap.classList.toggle("hidden",user.worker_type!=="ENGINEER"&&user.role==="USER");renderAddType();renderParticipants();await loadRecent();if(user.role!=="USER"){adminView.classList.remove("hidden");await loadDashboard()}else adminView.classList.add("hidden")}
async function logout(){await post(AUTH,{action:"logout",token:token});localStorage.removeItem("fctMealToken");location.reload()}
function renderAddType(){var external=(user&&(user.worker_type==="ENGINEER"||user.role!=="USER")&&addType.value==="external");employeeAdd.classList.toggle("hidden",external);externalAdd.classList.toggle("hidden",!external)}
async function addEmployeeCompanion(){var no=addNo.value.trim();if(!no)return;var j=await post(AUTH,{action:"lookup_employee",token:token,employee_no:no});if(!j.ok){alert(j.message);return}if(j.employee.employee_no===user.employee_no){alert("본인은 이미 자동 포함됩니다.");return}if(participants.some(function(p){return p.kind==="employee"&&p.employee_no===j.employee.employee_no})){alert("이미 추가된 사번입니다.");return}participants.push({kind:"employee",employee_no:j.employee.employee_no,name:j.employee.name,department:j.employee.department,worker_type:j.employee.worker_type});addNo.value="";renderParticipants()}
function addExternal(){var company=extCompany.value.trim(),name=extName.value.trim();if(!company||!name){alert("업체명과 이름을 입력하세요.");return}participants.push({kind:"external",company:company,name:name});extName.value="";renderParticipants()}
function removeP(i){participants.splice(i,1);renderParticipants()}
function renderParticipants(){var s='<div class="person"><div class="info"><b>'+esc(user?user.name:"")+' <span class="tag '+(user&&user.worker_type==="OP"?"op":"eng")+'">'+esc(user?(user.worker_type==="OP"?"OP":"엔지니어"):"")+'</span></b><span class="muted small">'+esc(user?user.department:"")+' · 본인</span></div></div>';participants.forEach(function(p,i){if(p.kind==="employee")s+='<div class="person"><div class="info"><b>'+esc(p.name)+' <span class="tag '+(p.worker_type==="OP"?"op":"eng")+'">'+esc(p.worker_type==="OP"?"OP":"엔지니어")+'</span></b><span class="muted small">'+esc(p.department)+' · '+esc(p.employee_no)+'</span></div><button class="danger auto" onclick="removeP('+i+')">삭제</button></div>';else s+='<div class="person"><div class="info"><b>'+esc(p.name)+' <span class="tag eng">외부 엔지니어</span></b><span class="muted small">'+esc(p.company)+'</span></div><button class="danger auto" onclick="removeP('+i+')">삭제</button></div>'});document.getElementById("participants").innerHTML=s}
async function submitMeal(){if(!restaurantId){msg("mealMsg","식당 QR로 접속해 주세요.",false);return}var body={action:"register",token:token,restaurant_id:restaurantId,participants:participants.map(function(p){return p.kind==="employee"?{kind:"employee",employee_no:p.employee_no}:{kind:"external",company:p.company,name:p.name}})};if(!manualMealType.classList.contains("hidden"))body.meal_type=manualMeal.value;var j=await post(REG,body);if(j.outside_meal_time){manualMealType.classList.remove("hidden");msg("mealMsg",j.message,false);return}msg("mealMsg",j.message+(j.skipped&&j.skipped.length?" / 중복 제외: "+j.skipped.join(", "):""),j.ok);if(j.ok){participants=[];renderParticipants();await loadRecent();if(user.role!=="USER")await loadDashboard()}}
async function loadRecent(){var j=await post(AUTH,{action:"my_recent",token:token});recentBody.innerHTML=j.ok&&j.records.length?j.records.map(function(r){return "<tr><td>"+esc(r.meal_date)+"</td><td>"+esc(String(r.meal_time).slice(0,8))+"</td><td>"+esc(r.restaurant_name)+"</td><td>"+(r.meal_type==="LUNCH"?"점심":"저녁")+"</td><td>"+esc(r.person_name)+"</td></tr>"}).join(""):'<tr><td colspan="5">등록내역이 없습니다.</td></tr>'}
function adminTab(n){document.querySelectorAll(".tabs [data-a]").forEach(function(b){b.classList.toggle("on",b.dataset.a===n)});document.querySelectorAll(".adminPanel").forEach(function(p){p.classList.remove("on")});document.getElementById("ap-"+n).classList.add("on");if(n==="users")loadUsers();if(n==="restaurants")loadRestaurants();if(n==="records")loadRecords();if(n==="settings")loadSettings()}
async function ac(action,x){var b=Object.assign({action:action,token:token},x||{});return post(ADM,b)}
function kstDate(d){return new Date(d.getTime()+9*3600000).toISOString().slice(0,10)}
async function loadDashboard(){var d=new Date(),today=kstDate(d),first=today.slice(0,7)+"-01";var j=await ac("meals",{from:first,to:today});if(!j.ok)return;adminRecords=j.records||[];var lunch=adminRecords.filter(function(x){return x.meal_date===today&&x.meal_type==="LUNCH"}).length,dinner=adminRecords.filter(function(x){return x.meal_date===today&&x.meal_type==="DINNER"}).length,op=adminRecords.filter(function(x){return x.meal_date===today&&x.worker_type==="OP"}).length,eng=adminRecords.filter(function(x){return x.meal_date===today&&x.worker_type==="ENGINEER"}).length,amount=adminRecords.reduce(function(s,x){return s+(x.meal_type==="LUNCH"?Number(x.lunch_price||0):Number(x.dinner_price||0))},0);kpis.innerHTML=[["오늘 점심",lunch+"식"],["오늘 저녁",dinner+"식"],["오늘 OP",op+"식"],["오늘 엔지니어",eng+"식"],["이번달 예상 식대",num(amount)+"원"]].map(function(x){return '<div class="kpi"><span class="muted small">'+x[0]+'</span><b>'+x[1]+'</b></div>'}).join("");dashSummary.innerHTML=summaryTable(adminRecords)}
function num(n){return new Intl.NumberFormat("ko-KR").format(n||0)}
async function loadUsers(){var j=await ac("users");if(!j.ok){alert(j.message);return}adminUsers=j.users||[];usersBody.innerHTML=adminUsers.map(function(x){var role=x.role==="OWNER"?"최초 마스터":x.role==="MASTER"?"마스터":"일반";var masterBtns="";if(user.role==="OWNER"&&x.role!=="OWNER")masterBtns=x.role==="MASTER"?'<button class="danger" onclick="setMaster(&quot;'+x.id+'&quot;,false)">마스터 해제</button>':'<button class="okbtn" onclick="setMaster(&quot;'+x.id+'&quot;,true)">마스터 지정</button>';var statusBtn=x.role==="OWNER"?'':' <button class="'+(x.active?'danger':'okbtn')+'" onclick="toggleUser(&quot;'+x.id+'&quot;,'+(!x.active)+')">'+(x.active?'사용중지':'사용복구')+'</button>';return '<tr><td>'+esc(x.employee_no)+'</td><td>'+esc(x.name)+'</td><td>'+esc(x.department)+'</td><td>'+(x.worker_type==="OP"?"OP":"엔지니어")+'</td><td>'+role+'</td><td>'+(x.active?"사용":"중지")+'</td><td><button class="btn2" onclick="editUser(&quot;'+x.id+'&quot;)">수정</button> '+masterBtns+statusBtn+'</td></tr>'}).join("")}
async function toggleUser(id,on){var x=adminUsers.find(function(y){return y.id===id});if(!x)return;if(!confirm(on?"이 직원을 사용 상태로 복구할까요?":"이 직원을 사용중지할까요?"))return;var j=await ac("save_user",{id:x.id,employee_no:x.employee_no,name:x.name,department:x.department,worker_type:x.worker_type,active:on});if(!j.ok){alert(j.message);return}await loadUsers()}
function clearUserForm(){euId.value="";euNo.value="";euNo.disabled=false;euName.value=""}
function editUser(id){var x=adminUsers.find(function(y){return y.id===id});if(!x)return;euId.value=x.id;euNo.value=x.employee_no;euNo.disabled=true;euName.value=x.name;euDept.value=x.department;euType.value=x.worker_type;scrollTo({top:document.getElementById("ap-users").offsetTop-70,behavior:"smooth"})}
async function saveUser(){var j=await ac("save_user",{id:euId.value,employee_no:euNo.value,name:euName.value,department:euDept.value,worker_type:euType.value,active:true});if(!j.ok){alert(j.message);return}clearUserForm();await loadUsers()}
async function setMaster(id,on){var pin="";if(on){pin=prompt("신규 마스터가 처음 로그인할 임시 PIN(숫자 4~8자리)을 입력하세요.")||"";if(!pin)return}if(!confirm(on?"마스터 권한을 부여할까요?":"마스터 권한을 해제할까요?"))return;var j=await ac("set_master",{id:id,enabled:on,pin:pin});alert(j.message|| (j.ok?"완료":"실패"));if(j.ok)loadUsers()}
async function importUsers(inp){var f=inp.files&&inp.files[0];if(!f)return;var buf=await f.arrayBuffer();var wb=XLSX.read(buf,{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:""});var j=await ac("bulk_users",{rows:rows});alert(j.ok?"처리 "+(j.created+j.updated)+"명 / 제외 "+j.skipped+"명":j.message);inp.value="";loadUsers()}
function downloadUsers(){var rows=adminUsers.map(function(x){return {"사번":x.employee_no,"이름":x.name,"부서":x.department,"구분":x.worker_type==="OP"?"OP":"엔지니어","권한":x.role,"상태":x.active?"사용":"중지"}});xlsx(rows,"FCT_직원목록.xlsx")}
async function loadRestaurants(){var j=await ac("restaurants");if(!j.ok){alert(j.message);return}adminRestaurants=j.restaurants||[];restaurantCards.innerHTML=adminRestaurants.map(function(r){var safeName=String(r.name||"").replace(/[\\/:*?"<>|']/g,"");return '<div class="qrcard"><div class="row"><div><b>'+esc(r.name)+'</b><div class="muted small">점심 '+num(r.lunch_price)+'원 / 저녁 '+num(r.dinner_price)+'원</div></div><span class="tag">'+(r.active?"사용중":"중지")+'</span></div><div class="qrbox" id="qr-'+r.id+'"></div><div class="row"><button class="btn2" onclick="editRestaurant(&quot;'+r.id+'&quot;)">수정</button><button class="btn2" onclick="downloadQr(&quot;'+r.id+'&quot;,&quot;'+safeName+'&quot;)">QR 저장</button><button class="'+(r.active?"danger":"okbtn")+'" onclick="toggleRestaurant(&quot;'+r.id+'&quot;,'+(!r.active)+')">'+(r.active?"사용중지":"사용")+'</button></div></div>'}).join("");setTimeout(function(){adminRestaurants.forEach(function(r){var e=document.getElementById("qr-"+r.id);if(e){e.innerHTML="";new QRCode(e,{text:location.origin+location.pathname+"?restaurant="+encodeURIComponent(r.id),width:180,height:180})}})},50)}
function clearRestaurantForm(){erId.value="";erName.value="";erLunch.value=0;erDinner.value=0}
function editRestaurant(id){var r=adminRestaurants.find(function(x){return x.id===id});if(!r)return;erId.value=r.id;erName.value=r.name;erLunch.value=r.lunch_price;erDinner.value=r.dinner_price;scrollTo({top:document.getElementById("ap-restaurants").offsetTop-70,behavior:"smooth"})}
async function saveRestaurant(){var j=await ac("save_restaurant",{id:erId.value,name:erName.value,lunch_price:erLunch.value,dinner_price:erDinner.value});if(!j.ok){alert(j.message);return}clearRestaurantForm();await loadRestaurants()}
async function toggleRestaurant(id,on){var j=await ac("toggle_restaurant",{id:id,active:on});if(!j.ok)alert(j.message);loadRestaurants()}
function downloadQr(id,name){var e=document.getElementById("qr-"+id),c=e&&e.querySelector("canvas"),im=e&&e.querySelector("img"),src=c?c.toDataURL("image/png"):im?im.src:"";if(!src)return;var a=document.createElement("a");a.href=src;a.download="FCT_"+name+"_QR.png";a.click()}
async function loadRecords(){if(!rf.value){var t=kstDate(new Date());rf.value=t.slice(0,7)+"-01";rt.value=t}var j=await ac("meals",{from:rf.value,to:rt.value});if(!j.ok){alert(j.message);return}adminRecords=j.records||[];recordSummary.innerHTML=summaryTable(adminRecords);recordsBody.innerHTML=adminRecords.length?adminRecords.map(function(x){var group=x.person_type==="EXTERNAL"?x.external_company:x.department;return '<tr><td>'+esc(x.meal_date)+'</td><td>'+esc(String(x.meal_time).slice(0,8))+'</td><td>'+esc(x.person_name)+'</td><td>'+esc(x.employee_no||"-")+'</td><td>'+esc(x.person_type==="EXTERNAL"?"외부 엔지니어":x.worker_type==="OP"?"OP":"엔지니어")+'</td><td>'+esc(group||"-")+'</td><td>'+esc(x.restaurant_name)+'</td><td>'+(x.meal_type==="LUNCH"?"점심":"저녁")+'</td><td>'+esc(x.registrant_name)+'</td><td><button class="danger" onclick="deleteMeal(&quot;'+x.id+'&quot;)">삭제</button></td></tr>'}).join(""):'<tr><td colspan="10">기록이 없습니다.</td></tr>'}
function summaryTable(rows){var m={};rows.forEach(function(x){var group=x.person_type==="EXTERNAL"?(x.external_company||"외부업체"):(x.department||"-"),kind=x.person_type==="EXTERNAL"?"외부 엔지니어":x.worker_type==="OP"?"OP":"엔지니어",key=x.restaurant_name+"|"+kind+"|"+group;if(!m[key])m[key]={restaurant:x.restaurant_name,kind:kind,group:group,l:0,d:0,amount:0};if(x.meal_type==="LUNCH"){m[key].l++;m[key].amount+=Number(x.lunch_price||0)}else{m[key].d++;m[key].amount+=Number(x.dinner_price||0)}});var arr=Object.values(m);return '<table><thead><tr><th>식당</th><th>구분</th><th>부서/업체</th><th>점심</th><th>저녁</th><th>총식수</th><th>금액</th></tr></thead><tbody>'+(arr.length?arr.map(function(x){return "<tr><td>"+esc(x.restaurant)+"</td><td>"+esc(x.kind)+"</td><td>"+esc(x.group)+"</td><td>"+x.l+"</td><td>"+x.d+"</td><td>"+(x.l+x.d)+"</td><td>"+num(x.amount)+"원</td></tr>"}).join(""):'<tr><td colspan="7">기록이 없습니다.</td></tr>')+"</tbody></table>"}
async function deleteMeal(id){if(!confirm("이 식사기록을 삭제할까요?"))return;var j=await ac("delete_meal",{id:id});if(!j.ok)alert(j.message);loadRecords()}
function downloadRecords(){var rows=adminRecords.map(function(x){return {"일자":x.meal_date,"시간":String(x.meal_time).slice(0,8),"이름":x.person_name,"사번":x.employee_no||"","구분":x.person_type==="EXTERNAL"?"외부 엔지니어":x.worker_type==="OP"?"OP":"엔지니어","부서/업체":x.person_type==="EXTERNAL"?x.external_company:x.department,"식당":x.restaurant_name,"식사":x.meal_type==="LUNCH"?"점심":"저녁","등록자":x.registrant_name,"금액":x.meal_type==="LUNCH"?x.lunch_price:x.dinner_price}});xlsx(rows,"FCT_식사기록_"+rf.value+"_"+rt.value+".xlsx")}
function xlsx(rows,name){var ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"목록");XLSX.writeFile(wb,name)}
async function loadSettings(){var j=await ac("settings");if(!j.ok){alert(j.message);return}var s=j.settings;ls.value=String(s.lunch_start).slice(0,5);le.value=String(s.lunch_end).slice(0,5);ds.value=String(s.dinner_start).slice(0,5);de.value=String(s.dinner_end).slice(0,5)}
async function saveSettings(){var j=await ac("save_settings",{lunch_start:ls.value,lunch_end:le.value,dinner_start:ds.value,dinner_end:de.value});alert(j.ok?"저장되었습니다.":j.message)}
async function changePin(){var j=await post(AUTH,{action:"change_pin",token:token,old_pin:oldPin.value,new_pin:newPin.value});alert(j.message);if(j.ok){oldPin.value="";newPin.value=""}}
(async function(){var t=kstDate(new Date());rf.value=t.slice(0,7)+"-01";rt.value=t;await loadRestaurant();await restore()})();
